name: r-core
channels:
  - conda-forge
dependencies:
  - r-base=4.2
  - quarto
  - deno
  - r-dplyr
  - r-fs
  - r-glue
  - r-yaml
  - r-here
  - r-ggplot2
  - r-purrr
  - r-readr
  - r-rlang
  - r-tidyr
  - r-jsonlite
  - r-knitr
  - r-rmarkdown
  - tectonic
