correct_only: true
rt_min_ms: 200
rt_max_ms: 2000

# Data sources 
raw_trials: data/raw/SCLP_full_TrialsSCLP.csv
raw_type: sclp_full   # one of: sclp_full, sample
cld_file: data/raw/chineselexicaldatabase2.1.txt
cld_type: full        # one of: full, sample
